# Generated by Django 5.2.4 on 2026-09-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_link_existing_staff_referrals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralclick',
            options={'ordering': ['-created_at']},
        ),
    ]
