# Generated by Django 5.2.4 on 2026-08-03 08:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionHubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_reference', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0.075'), max_digits=5)),
                ('matched', models.BooleanField(default=False)),
                ('match_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('manual', 'Manual')], max_length=20)),
                ('order_date', models.DateTimeField()),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='leads.lead')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='referrals.referral')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManualSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('service_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('pos', 'POS'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('sale_date', models.DateField()),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_sales', to='leads.lead')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_sales', to='referrals.referral')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
