# Generated by Django 5.2.4 on 2026-08-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_service_name_alter_lead_interest'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualsale',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='manualsale',
            name='referral',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=150)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('customer_first_name', models.CharField(blank=True, max_length=100)),
                ('customer_last_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_code', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('match_method', models.CharField(blank=True, max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('matched_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FashionHubOrder',
        ),
        migrations.DeleteModel(
            name='ManualSale',
        ),
    ]
