# Generated by Django 5.2.4 on 2026-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_customsale_financial_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsale',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Service value before VAT and refundable security deposit.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='customsale',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service value + VAT + refundable security deposit.', max_digits=12),
        ),
    ]
