# Generated by Django 5.2.4 on 2026-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_email_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interest',
            field=models.CharField(blank=True, choices=[('fashion_hub', 'FashionHub Purchase'), ('custom_service', 'Custom Service')], max_length=30),
        ),
    ]
