# Generated by Django 5.2.4 on 2026-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='interest',
            field=models.CharField(blank=True, choices=[('fashion_hub', 'Ananse Center for Design'), ('custom_service', 'Custom Service')], max_length=30),
        ),
    ]
